import logging
import os
from typing import Any, Dict, List, Optional, Tuple

from google import genai
from google.genai import errors as genai_errors

from src.domain.entities import ChatMessage, PredictionResult
from src.interfaces.gateways import LlmServiceGateway


CHAT_MODEL = "gemini-flash-latest"


class GeminiLlmService(LlmServiceGateway):
    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.logger.addHandler(logging.NullHandler())

        api_key = os.getenv("LLM_API_KEY") or os.getenv("GEMINI_API_KEY") or ""
        if not api_key:
            raise RuntimeError("GEMINI_API_KEY not set in environment")
        self.client = genai.Client(api_key=api_key)
        self.model = (os.getenv("LLM_MODEL") or CHAT_MODEL).strip()

    def generate_report_narrative(
        self, traditional_result: PredictionResult, cnn_result: PredictionResult
    ) -> str:
        context = self._build_diagnostic_context(traditional_result, cnn_result)
        prompt = self._build_prompt(context)
        try:
            text = self._call_llm(prompt)
            narrative = self._parse_narrative(text)
            return narrative or text
        except Exception as exc:
            self.logger.exception("LLM narrative generation failed")
            return self._fallback_narrative(traditional_result, cnn_result, str(exc))

    def _build_diagnostic_context(
        self, traditional_result: PredictionResult, cnn_result: PredictionResult
    ) -> Dict[str, Any]:
        features = traditional_result.extracted_features or {}
        return {
            "traditional_model_type": traditional_result.model_type,
            "traditional_prediction": traditional_result.prediction_label,
            "traditional_confidence": round(traditional_result.confidence_score, 3),
            "traditional_features": {
                key: round(value, 4) if isinstance(value, (int, float)) else value
                for key, value in features.items()
            },
            "cnn_model_type": cnn_result.model_type,
            "cnn_prediction": cnn_result.prediction_label,
            "cnn_confidence": round(cnn_result.confidence_score, 3),
            "cnn_grad_cam_path": cnn_result.grad_cam_path or "Unavailable",
            "cnn_per_class_probabilities": cnn_result.per_class_probabilities,
            "consensus_agreement": traditional_result.prediction_label
            == cnn_result.prediction_label,
        }

    def _build_prompt(self, context: Dict[str, Any]) -> str:
        import json
        system = (
            "You are a clinical-grade radiology AI assistant writing a cancer screening report for a chest X-ray. "
            "Use a structured, professional tone appropriate for an interdisciplinary clinical audience. "
            "Produce a concise HTML narrative with sections: Summary of findings, Detailed explanation of model predictions, "
            "Discussion of key features detected, Clinical recommendations and caveats, References to detected radiological patterns. "
            "Return the response as valid HTML using h3/h4 headings and paragraphs. "
            "Do not hallucinate findings not present in the diagnostic context."
        )
        return f"{system}\n\nDiagnostic Context:\n{json.dumps(context, indent=2, ensure_ascii=False)}"

    def _call_llm(self, prompt: str) -> str:
        try:
            resp = self.client.models.generate_content(
                model=self.model, contents=prompt
            )
            return resp.text.strip() if resp.text else ""
        except genai_errors.ClientError as e:
            raise RuntimeError(self._friendly_error(e)) from e

    def _parse_narrative(self, text: str) -> str:
        if not text or not text.strip():
            return ""
        import json as _json
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end > start:
            candidate = text[start : end + 1]
            try:
                payload = _json.loads(candidate)
                if isinstance(payload, dict) and isinstance(payload.get("narrative_html"), str):
                    return payload["narrative_html"].strip()
            except _json.JSONDecodeError:
                pass
        return text.strip()

    def _fallback_narrative(
        self, traditional_result: PredictionResult, cnn_result: PredictionResult, error: str
    ) -> str:
        return (
            "<h3>Diagnostic Narrative Unavailable</h3>"
            "<p>The narrative summary could not be generated by the configured language model.</p>"
            f"<p><strong>Traditional model:</strong> {traditional_result.prediction_label} "
            f"({traditional_result.confidence_score * 100:.1f}% confidence).</p>"
            f"<p><strong>CNN model:</strong> {cnn_result.prediction_label} "
            f"({cnn_result.confidence_score * 100:.1f}% confidence).</p>"
            f"<p><strong>Error:</strong> {error}</p>"
            "<p>Please confirm this scan with a qualified radiologist.</p>"
        )

    def chat_follow_up(
        self, history: List[ChatMessage], new_message: str, diagnostic_context: Dict[str, Any]
    ) -> str:
        prompt = self._build_chat_prompt(history, new_message, diagnostic_context)
        try:
            return self._call_llm(prompt)
        except Exception as exc:
            self.logger.exception("LLM chat follow-up failed")
            return (
                "I am unable to generate a chat response at this time. "
                "Please review the diagnostic context and try again later."
            )

    def _build_chat_prompt(
        self, history: List[ChatMessage], new_message: str, diagnostic_context: Dict[str, Any]
    ) -> str:
        import json
        system = (
            "You are a clinical decision support assistant for chest X-ray analysis. "
            "You have a full diagnostic context with per-class pathology probabilities (15 NIH classes), "
            "a traditional ML model prediction, and an AI narrative summary. "
            "Keep responses conversational but grounded in the provided data. "
            "Reference specific pathology names and percentages when relevant. "
            "You remember the full conversation history - build on previous exchanges naturally. "
            "If the user asks something not covered by the context, say so clearly. "
            "Always note that findings require clinical confirmation by a radiologist."
        )
        context_payload = json.dumps(diagnostic_context, indent=2, ensure_ascii=False)
        chat_history_text = "\n".join(
            f"{'User' if m.role == 'user' else 'Assistant'}: {m.content.strip()}" for m in history
        )
        return (
            f"{system}\n\n"
            f"Diagnostic Context:\n{context_payload}\n\n"
            f"Conversation History:\n{chat_history_text}\n\n"
            f"User Question:\n{new_message.strip()}"
        )

    @staticmethod
    def _friendly_error(err: genai_errors.ClientError) -> str:
        msg = str(err)
        code = getattr(err, "code", 0) or 0
        if not code:
            import re
            match = re.search(r"^(\d+)", msg)
            code = int(match.group(1)) if match else 0
        if code == 429:
            return "The AI service is temporarily out of requests due to quota limits. Please wait and try again."
        if code == 403:
            return "The AI service couldn't authenticate your API key. Please check your configuration."
        if code == 400:
            return "The request to the AI service was invalid. Try rephrasing your question."
        if code == 404:
            return "The AI model is not available. The service may be updating."
        return "The AI service returned an unexpected error. Please try again later."
